name: Bug Report
description: Something not working? Let us know.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Clear description of the bug
      placeholder: When I run /ralph-specum:start, it...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
      placeholder: It should have created specs/my-feature/research.md
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Run `/ralph-specum:new test-feature`
        2. Run `/ralph-specum:requirements`
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error messages or logs
      description: Copy any relevant error output
      render: shell
    validations:
      required: false

  - type: input
    id: claude-version
    attributes:
      label: Claude Code version
      description: Run `claude --version`
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows (WSL)
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else that might help
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and this is not a duplicate
          required: true
        - label: I restarted Claude Code after installing/updating the plugin
          required: true
